import {
  UserProfile,
  Ingredient,
  StockTransaction,
  DailyExpenditureSummary,
  CoordinatorAssignment,
  AuditLogEntry,
} from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  { id: 'usr-admin-1', name: 'Vignesh Rao', role: 'admin', email: 'jvigneshrao05@gmail.com', active: true },
  { id: 'usr-incharge-1', name: 'R. K. Sharma', role: 'incharge', email: 'incharge@hostel.edu', active: true },
  { id: 'usr-coord-1', name: 'Karthik Reddy', role: 'coordinator', email: 'karthik@student.hostel.edu', active: true },
  { id: 'usr-coord-2', name: 'Priya Sundaram', role: 'coordinator', email: 'priya@student.hostel.edu', active: true },
  { id: 'usr-coord-3', name: 'Ananya Verma', role: 'coordinator', email: 'ananya@student.hostel.edu', active: true },
];

export const INITIAL_INGREDIENTS: Ingredient[] = [
  {
    ingredient_id: 'ing-1',
    name: 'Sona Masoori Rice',
    name_telugu: 'సోనా మసూరి బియ్యం',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 420.5,
    current_price: 54.0,
  },
  {
    ingredient_id: 'ing-2',
    name: 'Toor Dal (Pappu)',
    name_telugu: 'కందిపప్పు',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 85.0,
    current_price: 148.0,
  },
  {
    ingredient_id: 'ing-3',
    name: 'Refined Sunflower Oil',
    name_telugu: 'సన్ ఫ్లవర్ నూనె',
    category: 'provisions',
    unit: 'litre',
    tracks_usage: true,
    active: true,
    current_stock: 64.0,
    current_price: 135.0,
  },
  {
    ingredient_id: 'ing-4',
    name: 'Chakki Fresh Atta',
    name_telugu: 'గోధుమ పిండి',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 110.0,
    current_price: 42.0,
  },
  {
    ingredient_id: 'ing-5',
    name: 'Moong Dal',
    name_telugu: 'పెసరపప్పు',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 35.0,
    current_price: 125.0,
  },
  {
    ingredient_id: 'ing-6',
    name: 'Refined Iodised Salt',
    name_telugu: 'ఉప్పు',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: false,
    active: true,
    current_stock: 40.0,
    current_price: 22.0,
  },
  {
    ingredient_id: 'ing-7',
    name: 'Sugar (M-Grade)',
    name_telugu: 'చక్కెర',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: false,
    active: true,
    current_stock: 50.0,
    current_price: 44.0,
  },
  {
    ingredient_id: 'ing-8',
    name: 'Tea Powder (Red Label)',
    name_telugu: 'టీ పొడి',
    category: 'provisions',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 14.5,
    current_price: 360.0,
  },
  {
    ingredient_id: 'ing-9',
    name: 'Fresh Toned Milk',
    name_telugu: 'పాలు',
    category: 'perishable',
    unit: 'litre',
    tracks_usage: true,
    active: true,
    current_stock: 45.0,
    current_price: 58.0,
  },
  {
    ingredient_id: 'ing-10',
    name: 'Country Farm Eggs',
    name_telugu: 'గుడ్లు',
    category: 'perishable',
    unit: 'piece',
    tracks_usage: true,
    active: true,
    current_stock: 240,
    current_price: 6.5,
  },
  {
    ingredient_id: 'ing-11',
    name: 'Fresh Tomatoes',
    name_telugu: 'టమాటాలు',
    category: 'perishable',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 28.0,
    current_price: 32.0,
  },
  {
    ingredient_id: 'ing-12',
    name: 'Nasik Red Onions',
    name_telugu: 'ఉల్లిపాయలు',
    category: 'perishable',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 55.0,
    current_price: 38.0,
  },
  {
    ingredient_id: 'ing-13',
    name: 'Fresh Potatoes (Aloo)',
    name_telugu: 'బంగాళాదుంపలు',
    category: 'perishable',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 40.0,
    current_price: 28.0,
  },
  {
    ingredient_id: 'ing-14',
    name: 'Malai Paneer Block',
    name_telugu: 'పన్నీర్',
    category: 'perishable',
    unit: 'kg',
    tracks_usage: true,
    active: true,
    current_stock: 12.0,
    current_price: 340.0,
  },
];

export function getInitialTransactions(): StockTransaction[] {
  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];

  return [
    {
      id: 'txn-1',
      ingredient_id: 'ing-1',
      txn_type: 'usage',
      quantity: -45,
      total_cost: 2430.0,
      usage_date: today,
      meal_type: 'lunch',
      vendor: null,
      reason: 'Regular lunch for 220 hostelers',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      created_by: 'usr-coord-1',
      created_by_name: 'Karthik Reddy',
      ingredients: { name: 'Sona Masoori Rice', category: 'provisions', unit: 'kg' },
    },
    {
      id: 'txn-2',
      ingredient_id: 'ing-2',
      txn_type: 'usage',
      quantity: -12,
      total_cost: 1776.0,
      usage_date: today,
      meal_type: 'lunch',
      vendor: null,
      reason: 'Tomato Pappu for lunch',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      created_by: 'usr-coord-1',
      created_by_name: 'Karthik Reddy',
      ingredients: { name: 'Toor Dal (Pappu)', category: 'provisions', unit: 'kg' },
    },
    {
      id: 'txn-3',
      ingredient_id: 'ing-9',
      txn_type: 'usage',
      quantity: -30,
      total_cost: 1740.0,
      usage_date: today,
      meal_type: null,
      vendor: null,
      reason: 'Morning tea and curds set',
      created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
      created_by: 'usr-coord-1',
      created_by_name: 'Karthik Reddy',
      ingredients: { name: 'Fresh Toned Milk', category: 'perishable', unit: 'litre' },
    },
    {
      id: 'txn-4',
      ingredient_id: 'ing-11',
      txn_type: 'purchase',
      quantity: 50,
      total_cost: 1600.0,
      usage_date: today,
      meal_type: null,
      vendor: 'Mandi Vegetable Trader - Shop #14',
      reason: null,
      created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
      created_by: 'usr-coord-1',
      created_by_name: 'Karthik Reddy',
      ingredients: { name: 'Fresh Tomatoes', category: 'perishable', unit: 'kg' },
    },
    {
      id: 'txn-5',
      ingredient_id: 'ing-3',
      txn_type: 'adjustment',
      quantity: -2.5,
      total_cost: 337.5,
      usage_date: yesterday,
      meal_type: null,
      vendor: null,
      reason: 'Spill / Accident - Tin seam leak during unloading',
      created_at: new Date(Date.now() - 86400000).toISOString(),
      created_by: 'usr-admin-1',
      created_by_name: 'Vignesh Rao',
      ingredients: { name: 'Refined Sunflower Oil', category: 'provisions', unit: 'litre' },
    },
    {
      id: 'txn-6',
      ingredient_id: 'ing-1',
      txn_type: 'purchase',
      quantity: 250,
      total_cost: 13500.0,
      usage_date: yesterday,
      meal_type: null,
      vendor: 'Sri Venkateswara Rice Mill',
      reason: null,
      created_at: new Date(Date.now() - 86400000 * 1.5).toISOString(),
      created_by: 'usr-admin-1',
      created_by_name: 'Vignesh Rao',
      ingredients: { name: 'Sona Masoori Rice', category: 'provisions', unit: 'kg' },
    },
  ];
}

export function getInitialSummaries(): Record<string, DailyExpenditureSummary> {
  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];

  return {
    [today]: {
      usage_date: today,
      total_expenditure: 5946.0,
      student_count: 218,
      guest_count: 6,
      total_people: 224,
      cost_per_head: 26.54,
    },
    [yesterday]: {
      usage_date: yesterday,
      total_expenditure: 7420.0,
      student_count: 222,
      guest_count: 4,
      total_people: 226,
      cost_per_head: 32.83,
    },
  };
}

export const INITIAL_ASSIGNMENTS: CoordinatorAssignment[] = [
  {
    id: 'asgn-1',
    user_id: 'usr-coord-1',
    duty_start_date: '2026-09-01',
    duty_end_date: '2026-09-30',
    created_by: 'usr-admin-1',
  },
  {
    id: 'asgn-2',
    user_id: 'usr-coord-2',
    duty_start_date: '2026-08-01',
    duty_end_date: '2026-08-31',
    created_by: 'usr-admin-1',
  },
  {
    id: 'asgn-3',
    user_id: 'usr-coord-3',
    duty_start_date: '2026-10-01',
    duty_end_date: '2026-10-31',
    created_by: 'usr-admin-1',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-1',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    user_id: 'usr-coord-1',
    user_name: 'Karthik Reddy',
    action: 'LOG_USAGE',
    entity_name: 'stock_transactions',
    highlight_reason: null,
    reason: 'Logged lunch usage of 45 kg Sona Masoori Rice (₹2,430.00)',
  },
  {
    id: 'aud-2',
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    user_id: 'usr-coord-1',
    user_name: 'Karthik Reddy',
    action: 'LOG_PURCHASE',
    entity_name: 'stock_transactions',
    highlight_reason: null,
    reason: 'Purchased 50 kg Fresh Tomatoes from Mandi Trader (₹1,600.00)',
  },
  {
    id: 'aud-3',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    user_id: 'usr-admin-1',
    user_name: 'Vignesh Rao',
    action: 'ADJUSTMENT',
    entity_name: 'stock_transactions',
    highlight_reason: 'adjustment',
    reason: 'Spill / Accident - Tin seam leak during unloading (-2.5 litre Refined Sunflower Oil)',
  },
  {
    id: 'aud-4',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    user_id: 'usr-coord-2',
    user_name: 'Priya Sundaram',
    action: 'GRACE_EDIT',
    entity_name: 'stock_transactions',
    highlight_reason: 'grace_edit',
    reason: 'Grace period correction: added late evening vegetable receipt voucher #402',
  },
  {
    id: 'aud-5',
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    user_id: 'usr-admin-1',
    user_name: 'Vignesh Rao',
    action: 'ASSIGN_DUTY',
    entity_name: 'coordinator_assignments',
    highlight_reason: null,
    reason: 'Assigned Karthik Reddy to September 2026 mess coordinator duty',
  },
];
